namespace Engine
{
    // This file is part of Micropolis for WinRT.
    // Copyright (C) 2014 Andreas Balzer, Felix Dietrich, Florian Thurnwald and Ivo Vutov
    // Portions Copyright (C) MicropolisJ by Jason Long
    // Portions Copyright (C) Micropolis Don Hopkins
    // Portions Copyright (C) 1989-2007 Electronic Arts Inc.
    //
    // Micropolis for WinRT is free software; you can redistribute it and/or modify
    // it under the terms of the GNU GPLv3, with Additional terms.
    // See the README file, included in this distribution, for details.
    // Project website: http://code.google.com/p/micropolis/

    /// <summary>
    ///     Enumeration of every possible message for the user generated by the game engine.
    /// </summary>
    public static class MicropolisMessages
    {
        // ReSharper disable InconsistentNaming
        //orig_num        generated       last tested/verified
        public static MicropolisMessage NEED_RES = new MicropolisMessage("NEED_RES");
        //   1            doMessages           1/19

        public static MicropolisMessage NEED_COM = new MicropolisMessage("NEED_COM");
        //   2            doMessages           1/19

        public static MicropolisMessage NEED_IND = new MicropolisMessage("NEED_IND");
        //   3            doMessages           1/19

        public static MicropolisMessage NEED_ROADS = new MicropolisMessage("NEED_ROADS");
        //   4            doMessages           1/19

        public static MicropolisMessage NEED_RAILS = new MicropolisMessage("NEED_RAILS");
        //   5            doMessages           1/20

        public static MicropolisMessage NEED_POWER = new MicropolisMessage("NEED_POWER");
        //   6            doMessages           1/19

        public static MicropolisMessage NEED_STADIUM = new MicropolisMessage("NEED_STADIUM");
        //   7            doMessages           1/20

        public static MicropolisMessage NEED_SEAPORT = new MicropolisMessage("NEED_SEAPORT");
        //   8            doMessages           1/20

        public static MicropolisMessage NEED_AIRPORT = new MicropolisMessage("NEED_AIRPORT");
        //   9            doMessages

        public static MicropolisMessage HIGH_POLLUTION = new MicropolisMessage("HIGH_POLLUTION");
        //  10            doMessages           1/20

        public static MicropolisMessage HIGH_CRIME = new MicropolisMessage("HIGH_CRIME");
        //  11            doMessages           1/19

        public static MicropolisMessage HIGH_TRAFFIC = new MicropolisMessage("HIGH_TRAFFIC");
        //  12            doMessages           1/20

        public static MicropolisMessage NEED_FIRESTATION = new MicropolisMessage("NEED_FIRESTATION");
        //  13            doMessages           1/19

        public static MicropolisMessage NEED_POLICE = new MicropolisMessage("NEED_POLICE");
        //  14            doMessages           1/19

        public static MicropolisMessage BLACKOUTS = new MicropolisMessage("BLACKOUTS");
        //  15            doMessages           1/19

        public static MicropolisMessage HIGH_TAXES = new MicropolisMessage("HIGH_TAXES");
        //  16            doMessages           1/19

        public static MicropolisMessage ROADS_NEED_FUNDING = new MicropolisMessage("ROADS_NEED_FUNDING");
        //  17            doMessages

        public static MicropolisMessage FIRE_NEED_FUNDING = new MicropolisMessage("FIRE_NEED_FUNDING");
        //  18            doMessages

        public static MicropolisMessage POLICE_NEED_FUNDING = new MicropolisMessage("POLICE_NEED_FUNDING");
        //  19            doMessages

        public static MicropolisMessage FIRE_REPORT = new MicropolisMessage("FIRE_REPORT"); //  20
        public static MicropolisMessage MONSTER_REPORT = new MicropolisMessage("MONSTER_REPORT");
        public static MicropolisMessage TORNADO_REPORT = new MicropolisMessage("TORNADO_REPORT");

        public static MicropolisMessage EARTHQUAKE_REPORT = new MicropolisMessage("EARTHQUAKE_REPORT");
        //  23            makeEarthquake

        public static MicropolisMessage PLANECRASH_REPORT = new MicropolisMessage("PLANECRASH_REPORT");
        public static MicropolisMessage SHIPWRECK_REPORT = new MicropolisMessage("SHIPWRECK_REPORT");
        public static MicropolisMessage TRAIN_CRASH_REPORT = new MicropolisMessage("TRAIN_CRASH_REPORT");
        public static MicropolisMessage COPTER_CRASH_REPORT = new MicropolisMessage("COPTER_CRASH_REPORT");
        public static MicropolisMessage HIGH_UNEMPLOYMENT = new MicropolisMessage("HIGH_UNEMPLOYMENT");
        public static MicropolisMessage OUT_OF_FUNDS_REPORT = new MicropolisMessage("OUT_OF_FUNDS_REPORT");
        public static MicropolisMessage FIREBOMBING_REPORT = new MicropolisMessage("FIREBOMBING_REPORT"); //30
        public static MicropolisMessage NEED_PARKS = new MicropolisMessage("NEED_PARKS");
        public static MicropolisMessage EXPLOSION_REPORT = new MicropolisMessage("EXPLOSION_REPORT");

        public static MicropolisMessage INSUFFICIENT_FUNDS = new MicropolisMessage("INSUFFICIENT_FUNDS");
        //  33            MainWindow.applyCurrentTool

        public static MicropolisMessage BULLDOZE_FIRST = new MicropolisMessage("BULLDOZE_FIRST");
        //  34            MainWindow.applyCurrentTool

        public static MicropolisMessage POP_2K_REACHED = new MicropolisMessage("POP_2K_REACHED");
        //  35            checkGrowth          1/19

        public static MicropolisMessage POP_10K_REACHED = new MicropolisMessage("POP_10K_REACHED");
        //  36            checkGrowth

        public static MicropolisMessage POP_50K_REACHED = new MicropolisMessage("POP_50K_REACHED");
        //  37            checkGrowth

        public static MicropolisMessage POP_100K_REACHED = new MicropolisMessage("POP_100K_REACHED");
        //  38            checkGrowth

        public static MicropolisMessage POP_500K_REACHED = new MicropolisMessage("POP_500K_REACHED");
        //  39            checkGrowth

        public static MicropolisMessage BROWNOUTS_REPORT = new MicropolisMessage("BROWNOUTS_REPORT");
        //  40                                 1/20

        public static MicropolisMessage HEAVY_TRAFFIC_REPORT = new MicropolisMessage("HEAVY_TRAFFIC_REPORT");
        //  41           HelicopterSprite

        public static MicropolisMessage FLOOD_REPORT = new MicropolisMessage("FLOOD_REPORT");

        public static MicropolisMessage MELTDOWN_REPORT = new MicropolisMessage("MELTDOWN_REPORT");
        // 43            doMeltdown

        public static MicropolisMessage RIOTING_REPORT = new MicropolisMessage("RIOTTING_REPORT");

        // Added by Jason
        public static MicropolisMessage NO_NUCLEAR_PLANTS = new MicropolisMessage("NO_NUCLEAR_PLANTS");

        public static MicropolisMessage SCENARIO_LOST = new MicropolisMessage("SCENARIO_LOST");
        public static MicropolisMessage SCENARIO_WON = new MicropolisMessage("SCENARIO_WON");

        public static MicropolisMessage SCENARIO_DULLSVILLE = new MicropolisMessage("SCENARIO_DULLSVILLE"); ///< 50: Dullsville scenario. 
        public static MicropolisMessage SCENARIO_SAN_FRANCISCO = new MicropolisMessage("SCENARIO_SAN_FRANCISCO"); ///< San Francisco scenario. 
        public static MicropolisMessage SCENARIO_HAMBURG = new MicropolisMessage("SCENARIO_HAMBURG"); ///< Hamburg scenario. 
        public static MicropolisMessage SCENARIO_BERN = new MicropolisMessage("SCENARIO_BERN"); ///< Bern scenario. 
        public static MicropolisMessage SCENARIO_TOKYO = new MicropolisMessage("SCENARIO_TOKYO"); ///< Tokyo scenario. 
        public static MicropolisMessage SCENARIO_DETROIT = new MicropolisMessage("SCENARIO_DETROIT"); ///< 55: Detroit scenario. 
        public static MicropolisMessage SCENARIO_BOSTON = new MicropolisMessage("SCENARIO_BOSTON"); ///< Boston scenario. 
        public static MicropolisMessage SCENARIO_RIO_DE_JANEIRO = new MicropolisMessage("SCENARIO_RIO_DE_JANEIRO"); ///< 57: Rio de Janeiro scenario. 


        // ReSharper restore InconsistentNaming
        /// <summary>
        ///     Initializes the <see cref="MicropolisMessages" /> class.
        /// </summary>
        static MicropolisMessages()
        {
            // not location-specific
            POP_2K_REACHED.UseNotificationPane = true;
            POP_10K_REACHED.UseNotificationPane = true;
            POP_50K_REACHED.UseNotificationPane = true;
            POP_100K_REACHED.UseNotificationPane = true;
            POP_500K_REACHED.UseNotificationPane = true;
            HIGH_CRIME.UseNotificationPane = true;
            HIGH_POLLUTION.UseNotificationPane = true;

            // location-specific
            FLOOD_REPORT.UseNotificationPane = true;
            FIRE_REPORT.UseNotificationPane = true;
            TORNADO_REPORT.UseNotificationPane = true;
            MELTDOWN_REPORT.UseNotificationPane = true;
            EARTHQUAKE_REPORT.UseNotificationPane = true;
            TRAIN_CRASH_REPORT.UseNotificationPane = true;
            SHIPWRECK_REPORT.UseNotificationPane = true;
            COPTER_CRASH_REPORT.UseNotificationPane = true;
            PLANECRASH_REPORT.UseNotificationPane = true;
            MONSTER_REPORT.UseNotificationPane = true;

            SCENARIO_WON.UseNotificationPane = true;
            SCENARIO_LOST.UseNotificationPane = true;

            SCENARIO_DULLSVILLE.UseNotificationPane = true;
            SCENARIO_SAN_FRANCISCO.UseNotificationPane = true;
            SCENARIO_HAMBURG.UseNotificationPane = true;
            SCENARIO_BERN.UseNotificationPane = true;
            SCENARIO_TOKYO.UseNotificationPane = true;
            SCENARIO_DETROIT.UseNotificationPane = true;
            SCENARIO_BOSTON.UseNotificationPane = true;
            SCENARIO_RIO_DE_JANEIRO.UseNotificationPane = true;

        }
    }
}