namespace Engine
{
    // This file is part of Micropolis for WinRT.
    // Copyright (C) 2014 Andreas Balzer, Felix Dietrich, Florian Thurnwald and Ivo Vutov
    // Portions Copyright (C) MicropolisJ by Jason Long
    // Portions Copyright (C) Micropolis Don Hopkins
    // Portions Copyright (C) 1989-2007 Electronic Arts Inc.
    //
    // Micropolis for WinRT is free software; you can redistribute it and/or modify
    // it under the terms of the GNU GPLv3, with Additional terms.
    // See the README file, included in this distribution, for details.
    // Project website: http://code.google.com/p/micropolis/

    /// <summary>
    ///     Contains the information generated by the query tool.
    ///     The numbers have very limited use, they are interpreted directly
    ///     by the showZoneStatus() method of NotificationPane.
    /// </summary>
    public class ZoneStatus
    {
        /// <summary>
        ///     The building type. Number from 0 to 27, identifying the type of building.
        /// </summary>
        public int Building;

        /// <summary>
        ///     The crime level. Number from 9 to 12, 9=Safe, 10=Light, 11=Moderate, etc.
        /// </summary>
        public int CrimeLevel;


        /// <summary>
        ///     The growth rate. Number from 17 to 20, 17=Declining, 18=Stable, etc.
        /// </summary>
        public int GrowthRate;

        /// <summary>
        ///     The land Value. Number from 5 to 8, 5=Slum, 6=Lower Class, etc.
        /// </summary>
        public int LandValue;

        /// <summary>
        ///     The pollution. Number from 13 to 16, 13=None, 14=Moderate, 15=Heavy, etc.
        /// </summary>
        public int Pollution;

        /// <summary>
        ///     The population density. Number from 1 to 4, 1=Low, 2=Medium, 3=High, 4=Very High.
        /// </summary>
        public int PopDensity;
    }
}